# Generated by Django 2.2.8 on 2019-12-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=120)),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('three_wheeler', 'Three Wheeler'), ('four_wheeler', 'Four Wheeler'), ('heavy', 'Heavy Vehicle')], max_length=120)),
                ('mobile_number', models.CharField(max_length=120)),
                ('id_staff', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_arrive', models.DateTimeField(auto_now_add=True)),
                ('time_leave', models.DateTimeField(null=True)),
                ('time_duration', models.DurationField()),
                ('vehicle_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logapp.Vehicle')),
            ],
        ),
    ]
