# Generated by Django 2.2.8 on 2019-12-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='time_arrive',
            new_name='time_arrival',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='id_staff',
            new_name='is_staff',
        ),
    ]
