# Generated by Django 2.2.8 on 2019-12-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_auto_20191231_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time_leave',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
